### ISSUE TITLE
Server Crashed and kept returning 500 internal server error

### ISSUE THREAD

**Issue by rockerguy1978** [jackm/kijiji-manager#10]
Hi,

I logged in and reposted all ads. That worked fine. When I went to view the main page again (can't remember if I refreshed or logged out and tried to log back in), I kept getting an internal server error. I am running this as a service on a Raspberry Pi on Ubuntu. Here are the journalctl logs

Trying to restart the service didn't fix the issue. I had to reboot the Pi and that seems to fix it. Anyways, hope this helps...

```
192.168.1.2 - - [08/Apr/2021 23:28:49] "GET / HTTP/1.1" 302 -
[2021-04-08 23:28:50,565] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/scripts/new_kijijireposter/kijiji-manager/kijiji_manager/views/main.py", line 25, in home
    return render_template('home.html', name=current_user.name, data=data)
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ubuntu/scripts/new_kijijireposter/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/scripts/new_kijijireposter/kijiji-manager/kijiji_manager/templates/home.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/ubuntu/scripts/new_kijijireposter/kijiji-manager/kijiji_manager/templates/layout.html", line 38, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ubuntu/scripts/new_kijijireposter/kijiji-manager/kijiji_manager/templates/home.html", line 56, in block "content"
    <td align="center">{{ ad['ad:rank']|adpage }}</td>
  File "/home/ubuntu/scripts/new_kijijireposter/kijiji-manager/kijiji_manager/views/main.py", line 89, in get_ad_page_number
    return int(math.ceil(int(data) / 20))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
192.168.1.2 - - [08/Apr/2021 23:28:50] "GET /home HTTP/1.1" 500 -
192.168.1.2 - - [08/Apr/2021 23:28:50] "GET /favicon.ico HTTP/1.1" 200 -
```

**Comment by rockerguy1978** [comment]
Just reviewed your most recent commit. I believe 0f62e0aaa2a42fd5 may address this issue.

**Comment by jackm** [comment]
Please do let me know if that latest commit resolves this issue

**Comment by rockerguy1978** [comment]
I haven't encountered the issue since I have pulled the latest commits. I'm going to close this off.
