### ISSUE TITLE
Docker Image update

### ISSUE THREAD

**Issue by mikekay1** [jackm/kijiji-manager#51]
I was wondering if I could somehow help update the image on docker hub to the newest version. 

Docker-compose up -d is not pulling latest.

**Comment by jackm** [comment]
The built image for this project is not actually hosted on Docker Hub. The base image is [tiangolo/meinheld-gunicorn-flask](https://hub.docker.com/r/tiangolo/meinheld-gunicorn-flask) which is on Docker Hub but that hasn't changed recently.

To build the latest image you will have to pull the master branch (or checkout a release tag) and run `docker-compose up --build` from the root of this repository to force a rebuild of the Docker image.

**Comment by mikekay1** [comment]
Thanks for the quick reply -- I think its trying to change something...

Getting the following error on the box that runs a few other docker images.

```
Successfully uninstalled Jinja2-3.0.2
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 2.0.1
    Uninstalling itsdangerous-2.0.1:
      Successfully uninstalled itsdangerous-2.0.1
  Attempting uninstall: click
    Found existing installation: click 8.0.3
    Uninstalling click-8.0.3:
      Successfully uninstalled click-8.0.3
  Attempting uninstall: Flask
    Found existing installation: Flask 2.0.1
    Uninstalling Flask-2.0.1:
      Successfully uninstalled Flask-2.0.1
Successfully installed Flask-2.1.3 Flask-Executor-0.10.0 Flask-Login-0.6.1 Flask-WTF-1.0.1 Jinja2-3.1.2 MarkupSafe-2.1.1 WTForms-3.0.1 Werkzeug-2.1.2 anyio-3.6.1 certifi-2022.6.15 charset-no
rmalizer-2.1.0 click-8.1.3 colorama-0.4.5 h11-0.12.0 httpcore-0.15.0 httpx-0.23.0 idna-3.3 importlib-metadata-4.12.0 is-safe-url-1.0 itsdangerous-2.1.2 numpy-1.21.6 pandas-1.3.5 pgeocode-0.3
.0 phonenumbers-8.12.52 python-dateutil-2.8.2 pytz-2022.1 requests-2.28.1 rfc3986-1.5.0 six-1.16.0 sniffio-1.2.0 typing-extensions-4.3.0 urllib3-1.26.10 xmltodict-0.13.0 zipp-3.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: ht
tps://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Removing intermediate container 3e41247dafb0
 ---> cb41bc712d2e
Step 6/6 : ENV MODULE_NAME=kijiji_manager.__main__
 ---> Running in 6cda8811d9ad
Removing intermediate container 6cda8811d9ad
 ---> e9b9d1f98410
Successfully built e9b9d1f98410
Successfully tagged kijiji-manager:latest
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.8/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/local/lib/python3.8/dist-packages/compose/project.py", line 664, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/local/lib/python3.8/dist-packages/compose/service.py", line 348, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/local/lib/python3.8/dist-packages/compose/service.py", line 1111, in build
    return builder.build(
  File "/usr/local/lib/python3.8/dist-packages/compose/service.py", line 1948, in build
    with open(iidfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpi5aupz3i'
mikekay@projectdock:~/docker-containers/kijiji-manager/kijiji-manager$ 

```

**Comment by jackm** [comment]
This looks like the same docker-compose bug that you ran into in #33 

See [docker issue #8121](https://github.com/docker/compose/issues/8121). Some suggestions are to make sure that both Docker and docker-compose are the latest version, and also possibly not using the Docker snap package and installing it as a regular system package.

**Comment by mikekay1** [comment]
Ah yes I think I used docker-snap but not sure too many production level containers to go back now. Thanks forgot I had this issue before! Thanks! When I repost the pictures don't pull over - My last comment was removed not sure what conclusion I came to.

**Comment by jackm** [comment]
> When I repost the pictures don't pull over

You'll have to elaborate on this - I'm not sure what you mean.

**Comment by jackm** [comment]
Do the image URLs in the ad payload XML file use the `media.kijiji.ca` domain or the `i.ebayimg.com` domain? The former is the current and correct image host domain.

**Comment by jackm** [comment]
Closing after no response from user for six months.
