### ISSUE TITLE
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'

### ISSUE THREAD

**Issue by JusticeGH** [jackm/kijiji-manager#66]
When trying to login via http://127.0.0.1:5000:
```
127.0.0.1 - - [02/May/2024 14:45:09] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [02/May/2024 14:45:09] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 14:45:09] "GET /static/login.css HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 14:45:09] "GET /favicon.ico HTTP/1.1" 200 -
[2024-05-02 14:45:18,356] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\kijiji_manager\kijijiapi.py", line 422, in _parse_response
    doc = xmltodict.parse(text)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\.venv\Lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: mismatched tag: line 2, column 56

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\.venv\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\.venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\.venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\.venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\kijiji_manager\views\user.py", line 27, in login
    user_id, token = kijiji_api.login(email, password)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\kijiji_manager\kijijiapi.py", line 94, in login
    doc = self._parse_response(r.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\kijiji_manager\kijijiapi.py", line 424, in _parse_response
    raise KijijiApiXmlException(f"Unable to parse text: {errors.messages[e.code]}", text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Justin\Documents\Python Projects\kijiji-manager\kijiji_manager\kijijiapi.py", line 27, in __init__
    user_dir = os.path.join(current_app.instance_path, 'user', current_user.id)
                                                               ^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
```

I tried running this through both conda and venv environments, same issue.

**Comment by jackm** [comment]
#67 would be the root cause of this
